/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Panel.java to edit this template
 */
package CLASES;

import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sopor
 */
public class PanelLocal extends java.awt.Panel {

    /**
     * Creates new form PanelLocal
     */
    public PanelLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxVendedoresVA = new javax.swing.JComboBox<>();
        jButtonAsignarVendedorVA = new javax.swing.JButton();
        jButtonQuitarGrupoVA = new javax.swing.JButton();
        jButtonAgregarGrupoVA = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelTablaVA = new javax.swing.JTabbedPane();

        jLabel1.setText("Vendedores");

        jButtonAsignarVendedorVA.setText("Asignar Vendedor");
        jButtonAsignarVendedorVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarVendedorVAActionPerformed(evt);
            }
        });

        jButtonQuitarGrupoVA.setText("Quitar Grupo");
        jButtonQuitarGrupoVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarGrupoVAActionPerformed(evt);
            }
        });

        jButtonAgregarGrupoVA.setText("Agregar Grupo");
        jButtonAgregarGrupoVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarGrupoVAActionPerformed(evt);
            }
        });

        jLabel2.setText("Grupo");

        jPanelTablaVA.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxVendedoresVA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAgregarGrupoVA, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonQuitarGrupoVA, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAsignarVendedorVA)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTablaVA)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxVendedoresVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAsignarVendedorVA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAgregarGrupoVA))
                    .addComponent(jButtonQuitarGrupoVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTablaVA, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAsignarVendedorVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarVendedorVAActionPerformed
        /*
        String nombreVendedorSeleccionado = jComboBoxVendedoresVA.getSelectedItem().toString(); //nombre de vendedor seleccionado
        int selectIndexVendedor = jComboBoxVendedoresVA.getSelectedIndex();
        int selectedIndex = jPanelTabla.getSelectedIndex();// panel a traves del index seleccionado
        JScrollPane name = (JScrollPane) jPanelTabla.getComponent(selectedIndex);//obtengo lo que esta dentro del panel
        JViewport name1 = (JViewport) name.getComponent(0);// obtengo lo visible
        JTable name2 = (JTable) name1.getComponent(0);// obtengo la tabla
        */
        
        String nombreVendedorSeleccionado = jComboBoxVendedoresVA.getSelectedItem().toString(); //nombre de vendedor seleccionado
        int selectIndexVendedor = jComboBoxVendedoresVA.getSelectedIndex();
        int selectedIndex = jPanelTablaVA.getSelectedIndex();
        JPanel name = (JPanel) jPanelTablaVA.getComponent(selectedIndex);
        JScrollPane name1 = (JScrollPane) name.getComponent(0);
        JViewport name2 = (JViewport) name1.getComponent(0);// obtengo lo visible
        int componentCount = name2.getComponentCount();
        System.out.println("componentCount" + componentCount);
        JTable name3 = (JTable) name2.getComponent(0);

        DefaultTableModel name4 = (DefaultTableModel) name3.getModel();//obtengo el modelo de la tabla
        Object[] fila = new Object[1];// fila, la que se llenara
        fila[0] = nombreVendedorSeleccionado;
        name4.addRow(fila); // se agrega a la fila el contenido de fila, el cual tiene el nombre del vendedor seleccionado.

        jComboBoxVendedoresVA.removeItemAt(selectIndexVendedor);
    }//GEN-LAST:event_jButtonAsignarVendedorVAActionPerformed

    private void jButtonQuitarGrupoVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarGrupoVAActionPerformed

        int countPanell = jPanelTablaVA.getTabCount();
        String text = "Grupo ";
        Component selectedComponent = jPanelTablaVA.getSelectedComponent();

        if (countPanell == 1) {
            jButtonQuitarGrupoVA.setEnabled(false);
            jButtonAsignarVendedorVA.setEnabled(false);
        }

        int selectedIndex = jPanelTablaVA.getSelectedIndex();// panel a traves del index seleccionado
        JScrollPane name = (JScrollPane) jPanelTablaVA.getComponent(selectedIndex);//obtengo lo que esta dentro del panel
        JViewport name1 = (JViewport) name.getComponent(0);// obtengo lo visible
        JTable name2 = (JTable) name1.getComponent(0);// obtengo la tabla

        for (int i = 0; i < name2.getRowCount(); i++) {
            String toString = name2.getValueAt(i, 0).toString();
            
//            if (selectedIndex == 0) {
//                jComboBoxVendedoresVA.addItem(toString);
//            } else if (selectedIndex == 1) {
//                jComboBoxVendedoresPB.addItem(toString);
//            } else if (selectedIndex == 2) {
//                jComboBoxVendedoresOL.addItem(toString);
//            }
        }

        jPanelTablaVA.remove(selectedIndex);
    }//GEN-LAST:event_jButtonQuitarGrupoVAActionPerformed

    private void jButtonAgregarGrupoVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarGrupoVAActionPerformed
        /*
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        javax.swing.JTable jTable1 = new javax.swing.JTable();
        javax.swing.JTable jTable2 = new javax.swing.JTable();
        javax.swing.JTable jTable3 = new javax.swing.JTable();
        javax.swing.JTextField jTextField1 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField2 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField3 = new javax.swing.JTextField();

        DefaultTableModel defaultTableModel1 = new DefaultTableModel();// creacion del modelo
        defaultTableModel1.addColumn("Nombre");// creacion de columna
        defaultTableModel1.addColumn("Quitar");// creacion de columna

        jTable1.setModel(defaultTableModel1);// modelo ingresado a la tabla

        DefaultTableModel defaultTableModel2 = new DefaultTableModel();// creacion del modelo
        defaultTableModel2.addColumn("Nombre");// creacion de columna
        defaultTableModel2.addColumn("Quitar");// creacion de columna

        jTable2.setModel(defaultTableModel2);// modelo ingresado a la tabla4

        DefaultTableModel defaultTableModel3 = new DefaultTableModel();// creacion del modelo
        defaultTableModel3.addColumn("Nombre");// creacion de columna
        defaultTableModel3.addColumn("Quitar");// creacion de columna4

        jTable3.setModel(defaultTableModel3);// modelo ingresado a la tabla

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jButton1.setText("Agregar");

        jScrollPane1.setViewportView(jTable1);
        jScrollPane2.setViewportView(jTable2);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addContainerGap())
        );
        */
        int auxPanel = 0;
        int componentCount = jPanelTablaVA.getTabCount();

        for (int i = 0; i < componentCount; i++) {
            String titleAt = jPanelTablaVA.getTitleAt(i);
            auxPanel = i + 1;
            System.out.println("componentCount " + componentCount);
        }

        String numCadena = String.valueOf(auxPanel + 1);
        jPanelTablaVA.addTab("Grupo: " + numCadena, new Panel());

        jButtonAsignarVendedorVA.setEnabled(true);

        /*int selectedIndex = jTabbedPane1.getSelectedIndex();

        String grupo = "Grupo ";
        int auxPanel = 0;

        JScrollPane jScrollPane = new JScrollPane();// scroll para ver completa la tabla
        JTable jTable = new JTable(); // creacion de la tabla

        DefaultTableModel defaultTableModel = new DefaultTableModel();// creacion del modelo
        defaultTableModel.addColumn("Nombre");// creacion de columna
        defaultTableModel.addColumn("Quitar");// creacion de columna

        jTable.setModel(defaultTableModel);// modelo ingresado a la tabla

        jTable.getColumn("Quitar").setCellRenderer(new PanelBotonRenderer());

        if (selectedIndex == 0) {
            jTable.getColumn("Quitar").setCellEditor(new PanelBotonEditor(jTable, jComboBoxVendedoresVA));
        } else if (selectedIndex == 1) {
            jTable.getColumn("Quitar").setCellEditor(new PanelBotonEditor(jTable, jComboBoxVendedoresPB));
        } else if (selectedIndex == 2) {
            jTable.getColumn("Quitar").setCellEditor(new PanelBotonEditor(jTable, jComboBoxVendedoresOL));
        }

        jTable.setShowHorizontalLines(true);
        jTable.setShowVerticalLines(true);
        jTable.setRowHeight(50);

        jScrollPane.setViewportView(jTable);//hace visible el panel del scroll

        int componentCount = jPanelTabla.getTabCount();

        for (int i = 0; i < componentCount; i++) {
            String titleAt = jPanelTabla.getTitleAt(i);
            auxPanel = i + 1;
            System.out.println("componentCount " + componentCount);
        }

        String numCadena = String.valueOf(auxPanel + 1);
        jPanelTabla.addTab(grupo + numCadena, jScrollPane);// agrego Panel y su nombre
        jButtonQuitarGrupo.setEnabled(true);
        jButtonAsignarVendedorjPanelTablaVA.setEnabled(true);
        */
    }//GEN-LAST:event_jButtonAgregarGrupoVAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarGrupoVA;
    public static javax.swing.JButton jButtonAsignarVendedorVA;
    private javax.swing.JButton jButtonQuitarGrupoVA;
    public static javax.swing.JComboBox<String> jComboBoxVendedoresVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JTabbedPane jPanelTablaVA;
    // End of variables declaration//GEN-END:variables
}
